export const Type ={
    FETCH_MESSAGE: "FETCH_MESSAGE",
    FETCH_MESSAGE_SUCCESS: "FETCH_MESSAGE_SUCCESS",
    FETCH_MESSAGE_FAILED: "FETCH_MESSAGE_FAILED",


    ADD_MESSAGE:"ADD_MESSAGE",
    ADD_MESSAGE_SUCCESS: "ADD_MESSAGE_SUCCESS",
    ADD_MESSAGE_FAILED: "ADD_MESSAGE_FAILED"


}